
@startuml
title Definición de transiciones de estados - EPIC-01 Gestión de Solicitudes de Compra
[*] --> CREADA
CREADA : Solicitante crea solicitud
CREADA --> EN_REVISIÓN : Solicitante envía la solicitud a Revisión
EN_REVISIÓN : EN REVISIÓN
EN_REVISIÓN --> APROBADA : Aprobador aprueba solicitud
EN_REVISIÓN --> RECHAZADA : Aprobador rechaza solicitud
APROBADA --> [*] : Estado final
RECHAZADA --> [*] : Estado final
@enduml
